version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - "./src:/var/www/html"
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"
  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - "./src:/var/www/html:rw"
  #     - ./docker/volumes/certbot/conf/:/etc/letsencrypt/:rw
