version: "3"

include:
  - ./../sapper/docker-compose-prod.yml
  - ./../ventScript/docker-compose-prod.yml

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - "./src:/var/www/html"
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - space

networks:
  space:
    driver: bridge