version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - "./src:/var/www/html"
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - titleSite

networks:
  titleSite:
    external: true
    name: titleSite
    driver: bridge